# Pythonイメージの取得
FROM python:3.8.6-slim-buster
# ワーキングディレクトリの指定
WORKDIR /usr/local/app
RUN apt update && apt install git -y
RUN git clone https://github.com/nuxt-image-board/backend
WORKDIR /usr/local/app/backend
# モジュールを揃える
RUN pip install --upgrade pip
RUN pip install -r requirements_worker.txt
# 起動環境設定
ENTRYPOINT ["rqworker"]
CMD [ "--url", "redis://nb_api_redis" ]